#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinScanner_Android.Resource", IsApplication=true)]

namespace XamarinScanner_Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Honeywell.AIDC.CrossPlatform.Resource.String.ApplicationName = global::XamarinScanner_Android.Resource.String.ApplicationName;
			global::Honeywell.AIDC.CrossPlatform.Resource.String.Hello = global::XamarinScanner_Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040011
			public const int Aztec = 2130968593;
			
			// aapt resource value: 0x7f040070
			public const int CenterDecode = 2130968688;
			
			// aapt resource value: 0x7f040014
			public const int Codabar = 2130968596;
			
			// aapt resource value: 0x7f040017
			public const int Codablock = 2130968599;
			
			// aapt resource value: 0x7f04001a
			public const int Code11 = 2130968602;
			
			// aapt resource value: 0x7f04001d
			public const int Code128 = 2130968605;
			
			// aapt resource value: 0x7f040020
			public const int Code39 = 2130968608;
			
			// aapt resource value: 0x7f040023
			public const int Code93 = 2130968611;
			
			// aapt resource value: 0x7f040026
			public const int DataMatrix = 2130968614;
			
			// aapt resource value: 0x7f040073
			public const int DecodeWinBot = 2130968691;
			
			// aapt resource value: 0x7f040076
			public const int DecodeWinLeft = 2130968694;
			
			// aapt resource value: 0x7f040079
			public const int DecodeWinRight = 2130968697;
			
			// aapt resource value: 0x7f04007c
			public const int DecodeWinTop = 2130968700;
			
			// aapt resource value: 0x7f04002c
			public const int EAN13 = 2130968620;
			
			// aapt resource value: 0x7f040029
			public const int EAN8 = 2130968617;
			
			// aapt resource value: 0x7f04002f
			public const int GS1128 = 2130968623;
			
			// aapt resource value: 0x7f040032
			public const int HanXin = 2130968626;
			
			// aapt resource value: 0x7f04003b
			public const int ISBT128 = 2130968635;
			
			// aapt resource value: 0x7f040035
			public const int Iata25 = 2130968629;
			
			// aapt resource value: 0x7f040038
			public const int Int25 = 2130968632;
			
			// aapt resource value: 0x7f040010
			public const int Item_1 = 2130968592;
			
			// aapt resource value: 0x7f04002b
			public const int Item_10 = 2130968619;
			
			// aapt resource value: 0x7f04002e
			public const int Item_11 = 2130968622;
			
			// aapt resource value: 0x7f040031
			public const int Item_12 = 2130968625;
			
			// aapt resource value: 0x7f040034
			public const int Item_13 = 2130968628;
			
			// aapt resource value: 0x7f040037
			public const int Item_14 = 2130968631;
			
			// aapt resource value: 0x7f04003a
			public const int Item_15 = 2130968634;
			
			// aapt resource value: 0x7f04003d
			public const int Item_16 = 2130968637;
			
			// aapt resource value: 0x7f040040
			public const int Item_17 = 2130968640;
			
			// aapt resource value: 0x7f040043
			public const int Item_18 = 2130968643;
			
			// aapt resource value: 0x7f040046
			public const int Item_19 = 2130968646;
			
			// aapt resource value: 0x7f040013
			public const int Item_2 = 2130968595;
			
			// aapt resource value: 0x7f040049
			public const int Item_20 = 2130968649;
			
			// aapt resource value: 0x7f04004f
			public const int Item_21 = 2130968655;
			
			// aapt resource value: 0x7f040052
			public const int Item_22 = 2130968658;
			
			// aapt resource value: 0x7f040055
			public const int Item_23 = 2130968661;
			
			// aapt resource value: 0x7f040058
			public const int Item_24 = 2130968664;
			
			// aapt resource value: 0x7f04005b
			public const int Item_25 = 2130968667;
			
			// aapt resource value: 0x7f04005e
			public const int Item_26 = 2130968670;
			
			// aapt resource value: 0x7f040061
			public const int Item_27 = 2130968673;
			
			// aapt resource value: 0x7f040064
			public const int Item_28 = 2130968676;
			
			// aapt resource value: 0x7f040067
			public const int Item_29 = 2130968679;
			
			// aapt resource value: 0x7f040016
			public const int Item_3 = 2130968598;
			
			// aapt resource value: 0x7f04006a
			public const int Item_30 = 2130968682;
			
			// aapt resource value: 0x7f04006c
			public const int Item_31 = 2130968684;
			
			// aapt resource value: 0x7f04006f
			public const int Item_32 = 2130968687;
			
			// aapt resource value: 0x7f040072
			public const int Item_33 = 2130968690;
			
			// aapt resource value: 0x7f040075
			public const int Item_34 = 2130968693;
			
			// aapt resource value: 0x7f040078
			public const int Item_35 = 2130968696;
			
			// aapt resource value: 0x7f04007b
			public const int Item_36 = 2130968699;
			
			// aapt resource value: 0x7f04004c
			public const int Item_37 = 2130968652;
			
			// aapt resource value: 0x7f040019
			public const int Item_4 = 2130968601;
			
			// aapt resource value: 0x7f04001c
			public const int Item_5 = 2130968604;
			
			// aapt resource value: 0x7f04001f
			public const int Item_6 = 2130968607;
			
			// aapt resource value: 0x7f040022
			public const int Item_7 = 2130968610;
			
			// aapt resource value: 0x7f040025
			public const int Item_8 = 2130968613;
			
			// aapt resource value: 0x7f040028
			public const int Item_9 = 2130968616;
			
			// aapt resource value: 0x7f04003e
			public const int Matrix25 = 2130968638;
			
			// aapt resource value: 0x7f040041
			public const int MaxiCode = 2130968641;
			
			// aapt resource value: 0x7f040044
			public const int MicroPDF417 = 2130968644;
			
			// aapt resource value: 0x7f040047
			public const int Msi = 2130968647;
			
			// aapt resource value: 0x7f04004d
			public const int PDF417 = 2130968653;
			
			// aapt resource value: 0x7f04004a
			public const int QRCode = 2130968650;
			
			// aapt resource value: 0x7f040050
			public const int RSS = 2130968656;
			
			// aapt resource value: 0x7f040053
			public const int RSSE = 2130968659;
			
			// aapt resource value: 0x7f040056
			public const int RSSL = 2130968662;
			
			// aapt resource value: 0x7f04006d
			public const int ReverseVideo = 2130968685;
			
			// aapt resource value: 0x7f04000e
			public const int Root = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int Save_Config_button = 2130968591;
			
			// aapt resource value: 0x7f04006b
			public const int ScannerOptions = 2130968683;
			
			// aapt resource value: 0x7f040059
			public const int Std25 = 2130968665;
			
			// aapt resource value: 0x7f04005c
			public const int Telepen = 2130968668;
			
			// aapt resource value: 0x7f04005f
			public const int Tlc39 = 2130968671;
			
			// aapt resource value: 0x7f040062
			public const int Trioptic = 2130968674;
			
			// aapt resource value: 0x7f040068
			public const int UPCA = 2130968680;
			
			// aapt resource value: 0x7f040065
			public const int UPCE = 2130968677;
			
			// aapt resource value: 0x7f040000
			public const int button1 = 2130968576;
			
			// aapt resource value: 0x7f04000c
			public const int config_symbologies = 2130968588;
			
			// aapt resource value: 0x7f040074
			public const int editText33 = 2130968692;
			
			// aapt resource value: 0x7f040077
			public const int editText34 = 2130968695;
			
			// aapt resource value: 0x7f04007a
			public const int editText35 = 2130968698;
			
			// aapt resource value: 0x7f04007d
			public const int editText36 = 2130968701;
			
			// aapt resource value: 0x7f040001
			public const int linearLayout1 = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int linearLayout2 = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int linearLayout3 = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int linearLayout4 = 2130968585;
			
			// aapt resource value: 0x7f04000b
			public const int linearLayout5 = 2130968587;
			
			// aapt resource value: 0x7f040003
			public const int openReaderSpinner = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int openReaderText = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int openScannerSwitch = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public const int scanButton = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int scanDataView = 2130968584;
			
			// aapt resource value: 0x7f04000d
			public const int scrollView1 = 2130968589;
			
			// aapt resource value: 0x7f040002
			public const int selectReaderText = 2130968578;
			
			// aapt resource value: 0x7f040012
			public const int switch1 = 2130968594;
			
			// aapt resource value: 0x7f04002d
			public const int switch10 = 2130968621;
			
			// aapt resource value: 0x7f040030
			public const int switch11 = 2130968624;
			
			// aapt resource value: 0x7f040033
			public const int switch12 = 2130968627;
			
			// aapt resource value: 0x7f040036
			public const int switch13 = 2130968630;
			
			// aapt resource value: 0x7f040039
			public const int switch14 = 2130968633;
			
			// aapt resource value: 0x7f04003c
			public const int switch15 = 2130968636;
			
			// aapt resource value: 0x7f04003f
			public const int switch16 = 2130968639;
			
			// aapt resource value: 0x7f040042
			public const int switch17 = 2130968642;
			
			// aapt resource value: 0x7f040045
			public const int switch18 = 2130968645;
			
			// aapt resource value: 0x7f040048
			public const int switch19 = 2130968648;
			
			// aapt resource value: 0x7f040015
			public const int switch2 = 2130968597;
			
			// aapt resource value: 0x7f04004b
			public const int switch20 = 2130968651;
			
			// aapt resource value: 0x7f040051
			public const int switch21 = 2130968657;
			
			// aapt resource value: 0x7f040054
			public const int switch22 = 2130968660;
			
			// aapt resource value: 0x7f040057
			public const int switch23 = 2130968663;
			
			// aapt resource value: 0x7f04005a
			public const int switch24 = 2130968666;
			
			// aapt resource value: 0x7f04005d
			public const int switch25 = 2130968669;
			
			// aapt resource value: 0x7f040060
			public const int switch26 = 2130968672;
			
			// aapt resource value: 0x7f040063
			public const int switch27 = 2130968675;
			
			// aapt resource value: 0x7f040066
			public const int switch28 = 2130968678;
			
			// aapt resource value: 0x7f040069
			public const int switch29 = 2130968681;
			
			// aapt resource value: 0x7f040018
			public const int switch3 = 2130968600;
			
			// aapt resource value: 0x7f04006e
			public const int switch31 = 2130968686;
			
			// aapt resource value: 0x7f040071
			public const int switch32 = 2130968689;
			
			// aapt resource value: 0x7f04004e
			public const int switch37 = 2130968654;
			
			// aapt resource value: 0x7f04001b
			public const int switch4 = 2130968603;
			
			// aapt resource value: 0x7f04001e
			public const int switch5 = 2130968606;
			
			// aapt resource value: 0x7f040021
			public const int switch6 = 2130968609;
			
			// aapt resource value: 0x7f040024
			public const int switch7 = 2130968612;
			
			// aapt resource value: 0x7f040027
			public const int switch8 = 2130968615;
			
			// aapt resource value: 0x7f04002a
			public const int switch9 = 2130968618;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Activity1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Main = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int SymbologiesActivity = 2130837506;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			// aapt resource value: 0x7f030002
			public const int app_name = 2130903042;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
